apiVersion: v1
kind: Pod
metadata:
  name: sharevol
spec:
  containers:
  - image: node-kube:volume
    imagePullPolicy: Never
    name: container1
    ports:
    volumeMounts:
    - mountPath: /cache1
      name: cache-volume
    env:
      - name: VOLUME_PATH
        value: /cache1 
  - image: busybox
    imagePullPolicy: Never
    name: container2
    command:
      - sleep
      - "10000"
    volumeMounts:
    - mountPath: /cache2
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
