apiVersion: v1
kind: Pod
metadata:
  name: consumesec
spec:
  containers:
  - name: node-kube
    image: node-kube:secret
    imagePullPolicy: Never
    ports:
    - containerPort: 4080
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret"
      readOnly: true
    env:
      - name: SECRET_PATH
        value: "/etc/secret"
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: username
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret2
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
data:
  username: YWRtaW4=
