apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /hello
          backend:
            serviceName: node-kube-service
            servicePort: 4080
---
apiVersion: v1
kind: Service
metadata:
  name: node-kube-service
spec:
  ports:
    - port: 4080
      protocol: TCP
      targetPort: 4080
  selector:
    app: node-kube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kube-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-kube
  template:
    metadata:
      labels:
        app: node-kube
        env: dev
        tier: frontend
    spec:
      containers:
      - name: node-kube
        image: node-kube:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 4080
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
